export enum responseEnum {
  UNIT_SET_TO_Post = 'Unit is set to Post',
  UNIT_Post_SUCCESS = 'Unit is set to Post',
  Post_STATUS_NOT_FOUND = 'There`s no such status property as Post',
  INPROGRESS_STATUS_NOT_FOUND = 'There`s no such status property as INPROGRESS',
  PostERS_EXISTS = 'Posters already exists',
  ALREADY_HELD = 'You have Post this unit already',
  UNIT_RELEASE_FROM_Post = 'Unit is released from Post',
  SALES_ALREADY_EXIST = 'Sales already exist',
  UNIT_NOT_FOUND = 'Unit not found',
  NO_PostERS = 'No Posters found',
  YOU_ARE_NOT_A_PostER = 'You are not a Poster',
  AVAILABLE_STATUS_NOT_FOUND = 'Available status not found',
  UN_Post_UNIT_SUCCESS = 'Unit is released from Post',
  REMOVE_UNIT_FROM_INPROGRESS = 'Unit is released from In-Progress',
  Post_NOT_FOUND_OR_NOT_HELD = 'Post not found or not held by you',
  GET_UNIT_PostER = 'Get unit Poster',
  UNIT_IS_SET_TO_INPROGRESS = 'Unit is set to in progress',
  YOU_CAN_NOT_PROCEED_WITH_THIS_UNIT = 'You can not proceed with this action',
}
